spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    defer-datasource-initialization: true
  main:
    allow-bean-definition-overriding: true
  test:
    mockmvc:
      print: default

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR
#          DEBUG
#          ERROR
#          FATAL
#          INFO
#          OFF
#          TRACE
server:
  port: 8080
#          WARN