CREATE TABLE users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_name UNIQUE (name);

CREATE TABLE items
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    price DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_items PRIMARY KEY (id)
);

ALTER TABLE items
    ADD CONSTRAINT uc_items_name UNIQUE (name);

CREATE TABLE orders
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name  VARCHAR(255)                            NOT NULL,
    amount     DOUBLE PRECISION,
    status     VARCHAR(255),
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

CREATE TABLE order_items
(
    item_id  BIGINT NOT NULL,
    order_id BIGINT NOT NULL
);

ALTER TABLE order_items
    ADD CONSTRAINT fk_ordite_on_item FOREIGN KEY (item_id) REFERENCES items (id);

ALTER TABLE order_items
    ADD CONSTRAINT fk_ordite_on_order FOREIGN KEY (order_id) REFERENCES orders (id);